
import './globals.css';

import Navbar from './components/Navbar/index';
import Footer from './components/Footer/Footer';
import { AnalyticsProvider } from './context/AnalyticsContext';
import PageViewTracker from './components/PageViewTracker';


export const metadata = {
  title: 'Klinik-UKOM',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AnalyticsProvider>
          <PageViewTracker />
          <Navbar />
          {children}
          <Footer />
        </AnalyticsProvider>
      </body>
    </html>
  )
}
